"""initial

Revision ID: 5f05d221bad8
Revises: 
Create Date: 2022-12-30 21:36:40.760126

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5f05d221bad8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brick',
    sa.Column('ID', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('designId', sa.Integer(), nullable=True),
    sa.Column('colorIds', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('item',
    sa.Column('ID', postgresql.UUID(as_uuid=True), nullable=False),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('master_data',
    sa.Column('ID', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('Normal', 'Novelty', 'Outgoing', 'Discontinued', name='itemstatus'), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('bricks_items',
    sa.Column('brick_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('item_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['brick_id'], ['brick.ID'], ),
    sa.ForeignKeyConstraint(['item_id'], ['item.ID'], ),
    sa.PrimaryKeyConstraint('brick_id', 'item_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bricks_items')
    op.drop_table('master_data')
    op.drop_table('item')
    op.drop_table('brick')
    # ### end Alembic commands ###
