"""associate MasterData to Item

Revision ID: ac1956874e19
Revises: 95986182efb9
Create Date: 2022-12-31 20:36:58.863433

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ac1956874e19'
down_revision = '95986182efb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('master_data_id', postgresql.UUID(as_uuid=True), nullable=True))
        batch_op.create_foreign_key(None, 'master_data', ['master_data_id'], ['id'])

    with op.batch_alter_table('master_data', schema=None) as batch_op:
        batch_op.drop_constraint('master_data_item_id_fkey', type_='foreignkey')
        batch_op.drop_column('item_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('master_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_id', postgresql.UUID(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('master_data_item_id_fkey', 'item', ['item_id'], ['id'])

    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('master_data_id')

    # ### end Alembic commands ###
