"""snake case on design and color ids

Revision ID: e2deee1d4007
Revises: 7df81ecce72c
Create Date: 2022-12-31 16:24:43.963107

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e2deee1d4007'
down_revision = '7df81ecce72c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brick', schema=None) as batch_op:
        batch_op.add_column(sa.Column('design_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('color_ids', postgresql.ARRAY(sa.Integer()), nullable=True))
        batch_op.drop_column('designId')
        batch_op.drop_column('colorIds')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brick', schema=None) as batch_op:
        batch_op.add_column(sa.Column('colorIds', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('designId', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('color_ids')
        batch_op.drop_column('design_id')

    # ### end Alembic commands ###
